#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "hal.h"

void Error_Handler(void);

#define B1_Pin GPIO_PIN_13
#define B1_GPIO_Port GPIOC
#define LPUART1_TX_Pin GPIO_PIN_2
#define LPUART1_TX_GPIO_Port GPIOA
#define LPUART1_RX_Pin GPIO_PIN_3
#define LPUART1_RX_GPIO_Port GPIOA

#define T_SWDIO_Pin GPIO_PIN_13
#define T_SWDIO_GPIO_Port GPIOA
#define T_SWCLK_Pin GPIO_PIN_14
#define T_SWCLK_GPIO_Port GPIOA
#define T_SWO_Pin GPIO_PIN_3
#define T_SWO_GPIO_Port GPIOB

#define INPUT_DISPLAY_SPI SPI1

#define INPUT_DISPLAY_MOSI_PORT GPIOB
#define INPUT_DISPLAY_MOSI_PIN GPIO_PIN_5
#define INPUT_DISPLAY_MISO_PORT GPIOB
#define INPUT_DISPLAY_MISO_PIN GPIO_PIN_4
#define INPUT_DISPLAY_SCK_PORT GPIOB
#define INPUT_DISPLAY_SCK_PIN GPIO_PIN_3
// #define DISPLAY_CS_PORT GPIOA
// #define DISPLAY_CS_PIN GPIO_PIN_4
#define INPUT_DISPLAY_CS_PORT GPIOA
#define INPUT_DISPLAY_CS_PIN GPIO_PIN_9
#define INPUT_DISPLAY_DI_PORT GPIOB
#define INPUT_DISPLAY_DI_PIN GPIO_PIN_6
#define INPUT_DISPLAY_RST_PORT GPIOB
#define INPUT_DISPLAY_RST_PIN GPIO_PIN_9

#define OUTPUT_DISPLAY_SPI SPI2

#define OUTPUT_DISPLAY_MOSI_PORT GPIOB
#define OUTPUT_DISPLAY_MOSI_PIN GPIO_PIN_15
#define OUTPUT_DISPLAY_MISO_PORT GPIOB
#define OUTPUT_DISPLAY_MISO_PIN GPIO_PIN_14
#define OUTPUT_DISPLAY_SCK_PORT GPIOB
#define OUTPUT_DISPLAY_SCK_PIN GPIO_PIN_13
#define OUTPUT_DISPLAY_CS_PORT GPIOB
#define OUTPUT_DISPLAY_CS_PIN GPIO_PIN_12
#define OUTPUT_DISPLAY_DC_PORT GPIOB
#define OUTPUT_DISPLAY_DC_PIN GPIO_PIN_11
#define OUTPUT_DISPLAY_RST_PORT GPIOB
#define OUTPUT_DISPLAY_RST_PIN GPIO_PIN_10

#define LD2_Pin GPIO_PIN_5
#define LD2_GPIO_Port GPIOA

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
